#!/usr/bin/env python3
"""Top-10 monthly downloads chart (Core AI models only) -> charts/hf-top.svg.

Embedded by the zoo README; regenerated by the weekly metrics Action.
Needs matplotlib.
"""

import csv

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

BLUE, INK, INK2, GRID = "#2a78d6", "#333333", "#666666", "#e6e6e6"

rows = list(csv.DictReader(open("stats/hf-downloads.csv")))
snaps = sorted({r["snapshot_date"] for r in rows})
latest = [r for r in rows if r["snapshot_date"] == snaps[-1]
          and "coreai" in r["model"].lower()]
top = sorted(latest, key=lambda r: int(r["downloads"]))[-10:]

fig, ax = plt.subplots(figsize=(7, 0.42 * len(top) + 1.1), dpi=100)
ax.set_facecolor("white")
for side in ("top", "right"):
    ax.spines[side].set_visible(False)
for side in ("left", "bottom"):
    ax.spines[side].set_color("#bbbbbb")
ax.tick_params(colors=INK2, labelsize=8)
ax.xaxis.grid(True, color=GRID, linewidth=0.8)
ax.set_axisbelow(True)

names = [r["model"].split("/")[1].replace("-CoreAI", "") for r in top]
vals = [int(r["downloads"]) for r in top]
bars = ax.barh(range(len(top)), vals, 0.62, color=BLUE)
for i, v in enumerate(vals):
    ax.annotate(str(v), (v, i), xytext=(4, 0), textcoords="offset points",
                va="center", fontsize=8, color=INK)
ax.set_yticks(range(len(top)))
ax.set_yticklabels(names, fontsize=8, color=INK)
ax.set_title(f"Most downloaded this month (Hugging Face, {snaps[-1]})",
             loc="left", fontsize=11, color=INK, pad=10)

import os
os.makedirs("charts", exist_ok=True)
fig.savefig("charts/hf-top.svg", bbox_inches="tight", facecolor="white")
print("charts/hf-top.svg")
